Fix no such file errors due to filenames in mkbootimg and unpackbootimg being inconsistent
The error from running `./build.sh` was:

```
  CAT     arch/arm64/boot/Image.gz-dtb
make[1]: Leaving directory '/usr/src/kernel/out'
make: Leaving directory '/usr/src/kernel'
ANDROID! magic found at: 0
BOARD_KERNEL_CMDLINE bootopt=64S3,32N2,64N2 buildvariant=user
BOARD_KERNEL_BASE 0x40078000
BOARD_NAME
BOARD_PAGE_SIZE 2048
BOARD_HASH_TYPE sha1
BOARD_KERNEL_OFFSET 0x00008000
BOARD_RAMDISK_OFFSET 0x07c08000
BOARD_SECOND_OFFSET 0xbff88000
BOARD_TAGS_OFFSET 0x0bc08000
BOARD_OS_VERSION 11.0.0
BOARD_OS_PATCH_LEVEL 2022-01
BOARD_HEADER_VERSION 2
BOARD_HEADER_SIZE 1660
BOARD_DTB_SIZE 171465
BOARD_DTB_OFFSET 0x0bc08000
cat: /var/tmp/bootimg/boot.img-base: No such file or directory
cat: /var/tmp/bootimg/boot.img-board: No such file or directory
cat: /var/tmp/bootimg/boot.img-cmdline: No such file or directory
cat: /var/tmp/bootimg/boot.img-dtb_offset: No such file or directory
cat: /var/tmp/bootimg/boot.img-hashtype: No such file or directory
cat: /var/tmp/bootimg/boot.img-header_version: No such file or directory
cat: /var/tmp/bootimg/boot.img-kernel_offset: No such file or directory
cat: /var/tmp/bootimg/boot.img-os_patch_level: No such file or directory
cat: /var/tmp/bootimg/boot.img-os_version: No such file or directory
cat: /var/tmp/bootimg/boot.img-pagesize: No such file or directory
cat: /var/tmp/bootimg/boot.img-ramdisk_offset: No such file or directory
cat: /var/tmp/bootimg/boot.img-second_offset: No such file or directory
cat: /var/tmp/bootimg/boot.img-tags_offset: No such file or directory
error: unknown hash algorithm ''
```

The files produced in `/var/tmp/bootimg` were instead called:

```
android_boot_a_astro.img-base
android_boot_a_astro.img-board
android_boot_a_astro.img-cmdline
android_boot_a_astro.img-dtb
android_boot_a_astro.img-dtb_offset
android_boot_a_astro.img-hashtype
android_boot_a_astro.img-header_version
android_boot_a_astro.img-kernel
android_boot_a_astro.img-kernel_offset
android_boot_a_astro.img-os_patch_level
android_boot_a_astro.img-os_version
android_boot_a_astro.img-pagesize
android_boot_a_astro.img-ramdisk
android_boot_a_astro.img-ramdisk_offset
android_boot_a_astro.img-second_offset
android_boot_a_astro.img-tags_offset
```

Renaming the boot image to a consistent name before unpacking ensures consistency in the output filenames.